### ISSUE TITLE
Possible improvement

### ISSUE THREAD

**Issue by andreasdc** [Fallen-Breath/fast-ip-ping#1]
### Motivation

faster pinging

### Description

Hey, I just found this mod, is it possible to get some kind of cache or other improvement?

**Comment by Fallen-Breath** [comment]
If you mean local DNS cache, I don't think that's really a good idea, since caching might lead to inaccurate result in some usage scenarios. Also, you can also just set a fast DNS provider for your operation system

**Comment by andreasdc** [comment]
> If you mean local DNS cache, I don't think that's really a good idea, since caching might lead to inaccurate result in some usage scenarios. Also, you can also just set a fast DNS provider for your operation system

Yea I use 1.1.1.1 or 8.8.8.8, but pinging in MC is tragic.

**Comment by Fallen-Breath** [comment]
Then you might try to find a better way to improve your dns resolution speed. Unless it's related to this mod, e.g. this mod not working / some other unresolved similar Minecraft issue, then I'll not gonna try to do find some optimizations without any directions

**Comment by andreasdc** [comment]
Example bug reports:
https://bugs.mojang.com/browse/MC-101789
https://bugs.mojang.com/browse/MC-256456
https://bugs.mojang.com/browse/MC-125762 (with possible solution?)
I can help with testing or checking a debug version to see what is going on.
Also I think refreshing or joining a server doesn't close pending connections.
Having offline server on the list messes up pinging too.

**Comment by Fallen-Breath** [comment]
The bug reports you given aren't related to this mod tho, and this mod isn't designed as an all-in-one optimzation mod that fixes all pinging related issues

**Comment by andreasdc** [comment]
I thought that when you said 'some other unresolved similar Minecraft issue' that you would be interested in fixing that :/

**Comment by andreasdc** [comment]
I found the big issue. When you have open Minecraft and you enable or disable VPN, next pings are insanely slow. When you restart Minecraft it is back to normal. Is it possible to fix that?

**Comment by Fallen-Breath** [comment]
> I found the big issue. When you have open Minecraft and you enable or disable VPN, next pings are insanely slow. When you restart Minecraft it is back to normal. Is it possible to fix that?

How does that related to this mod? Is it also a dns reversed lookup issue (i.e. only affects servers with ip-only hostname)?

If it is, you can create another issue for feature request on this kind of unfixed reversed dns lookup

If it's not, and is just a general optimization idea, see https://github.com/Fallen-Breath/fast-ip-ping/issues/1#issuecomment-1707653214

**Comment by andreasdc** [comment]
I thought that you can be good person to reach out with it. If you want I can create another issue just with this bug.

**Comment by andreasdc** [comment]
It might be related Unable to start LAN server detection: No route to host: setsocketopt

**Comment by andreasdc** [comment]
I think adding just timeout will help with that

**Comment by Fallen-Breath** [comment]
Still, see https://github.com/Fallen-Breath/fast-ip-ping/issues/1#issuecomment-1707653214, this is not a general network optimization mod

**Comment by andreasdc** [comment]
> Still, see [#1 (comment)](https://github.com/Fallen-Breath/fast-ip-ping/issues/1#issuecomment-1707653214), this is not a general network optimization mod

It always could be, right? 😄 That's a relatively small change and would massively help.
