### ISSUE TITLE
1.21 update

### ISSUE THREAD

**Issue by DeadLector** [Fallen-Breath/fast-ip-ping#2]
### Bug description

1.20.6 version is not working on 1.21. I need a update for it!

### Steps to reproduce

Just try any earlier version in minecraft 1.21

### Expected behavior

For it to start minecraft and hide the gizmo.

### Actual behavior

Minecraft crash on launch.

### Minecraft version

1.21

### Fast IP Ping version

1.0.1

### Check list

- [X] I have verified that the issue persists in the latest version of the mod.
- [X] I have searched the existing issues and confirmed that this is not a duplicate.

**Comment by Fallen-Breath** [comment]
https://github.com/Fallen-Breath/fast-ip-ping/releases/tag/v1.0.2
